#version: '3.8'

services:
  #--- Contenedor de la aplicación Laravel/PHP ---#
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args: # <-- REEMPLAZA ESTA SECCIÓN ENTERA
        user: uzilinux
        uid: 1000
    container_name: opiniones-api-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - opiniones-api-network

  #--- Contenedor del Servidor Web Nginx ---#
  nginx:
    image: nginx:alpine
    container_name: opiniones-api-nginx
    restart: unless-stopped
    ports:
      - "8080:80" # Accederás a la app desde http://localhost:8080
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - opiniones-api-network
    depends_on:
      - app

networks:
  opiniones-api-network:
    driver: bridge