services:
  - type: web
    name: opiniones-turisticas-api
    plan: free
    env: docker
    dockerfilePath: ./docker/Dockerfile  # ✅ Ruta corregida
    healthCheckPath: /api/health          # Puedes desactivarlo si no tienes esa ruta
    http:
      port: 8000                          # ✅ Este puerto debe coincidir con el que expone tu Dockerfile
    envVars:
      - key: APP_URL
        value: https://${RENDER_EXTERNAL_URL}
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mongodb
      - key: DB_URI
        sync: false  # ⚠️ Recuerda configurarlo manualmente en el dashboard de Render
