services:
  - type: web
    name: opiniones-turisticas-api
    plan: free 
    env: docker
    dockerfilePath: ./Dockerfile.render
    healthCheckPath: /api/health
    envVars:
      - key: APP_URL
        value: https://${RENDER_EXTERNAL_URL}
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mongodb
      - key: DB_URI
        sync: false # Remember to set this in the Render dashboard