services:
  - type: web
    name: opiniones-turisticas-api
    plan: free
    env: docker
    dockerfilePath: ./docker/Dockerfile  
    healthCheckPath: /api/health
    ports:
      - 80 # ¡Aquí está la clave!
    envVars:
      - key: APP_URL
        value: https://${RENDER_EXTERNAL_URL}
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mongodb
      - key: DB_URI
        sync: false

