services:
  - type: web
    name: opiniones-turisticas-api
    env: docker
    dockerfilePath: ./Dockerfile.render # Usa el nuevo Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: APP_URL
        value: https://${RENDER_EXTERNAL_URL}
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mongodb
      - key: DB_URI
        sync: false # Lo configuraremos manualmente
    disk:
      name: laravel-storage
      mountPath: /var/www/html/storage
      sizeGB: 1