services:
  - type: web
    name: opiniones-turisticas-api
    plan: free
    env: docker
    dockerfilePath: ./docker/Dockerfile
    buildCommand: |-
      npm install
      npm run build
      php artisan migrate --force
    http:
      port: 80
    envVars:
      - key: APP_URL
        value: https://${RENDER_EXTERNAL_URL}
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mongodb
      - key: DB_URI
        sync: false

